### PR TITLE
Added support for github-integration-plugin

### PR DESCRIPTION
**Pull request by miklis**
https://github.com/jenkinsci/github-integration-plugin triggers builds from Github pull requests. We want to see pull request badges with the builds triggered with this plugin.

### CODE REVIEW

**Comment by batmat** [comment]
Thanks!

**Comment by KostyaSha** [comment]
Plugin has it's own badge now.  And question need to be removed...

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/buildtriggerbadge-plugin/pull/22

**Comment by KostyaSha** [comment]
Ok, and question need to be fixed by using disabling extension. Will handle on my side (hopefully this plugin has no additional dependencies).

**Comment by batmat** [comment]
@kostyasha please see the wiki page of the plugin. There's a note about finding the cause on an existing build, (to be sure about the one in use) then just put it here I'll add it and release today.

Thanks

**Comment by batmat** [comment]
OK re-read. Got it. Nvm.

**Comment by KostyaSha** [comment]
@batmat plugin has additional badge for branch triggers, that why i was bit confused.

**Comment by jgangemi** [comment]
@batmat is it possible to revert this change given the plugin provides its own badge?

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/buildtriggerbadge-plugin/pull/22 is still not merged.

**Pull request merged**
