### PR TITLE
Replace PNG with SVG icons

### PR DESCRIPTION
**Pull request by NotMyFault**
This pull request aims to replace existing PNG images with modern SVG ionicons, like they are already used partly in core:

<details>
<summary>Current look light theme 1/2</summary>

</details>

<details>
<summary>Current look light theme 2/2</summary>

</details>

</details>

<details>
<summary>Current look dark theme 1/2</summary>

</details>

<details>
<summary>Current look dark theme 2/2</summary>

</details>

<hr noshade>

<details>
<summary>Proposed change light theme 1/2</summary>

</details>

<details>
<summary>Proposed change light theme 2/2</summary>

</details>

<details>
<summary>Proposed change dark theme 1/2</summary>

</details>

<details>
<summary>Proposed change dark theme 2/2</summary>

</details>

Also fixes a little typo when overriding icons.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira: https://issues.jenkins.io/browse/JENKINS-66438
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by NotMyFault** [comment]
@batmat Is there anything that blocks a merge (or review)?

**Comment by NotMyFault** [comment]
@batmat Do you mind taking a look over the PR? :)

**Comment by batmat** [comment]
Sorry for taking so long. The main reason is that I'm unsure I want this. This plugin is my first Jenkins plugin and kind of my baby you know :). I've done some of these icons myself (ok, they probably don't look awesome, but they were done with love :grin:).

I see the point on consistency, for sure. But I need to look at these icons to see if I really agree with the replacement.

If you don't mind, I would appreciate a side by side comparison of before/after icons.

Sorry again for the lag.

**Comment by NotMyFault** [comment]
> Sorry for taking so long. The main reason is that I'm unsure I want this. This plugin is my first Jenkins plugin and kind of my baby you know :). I've done some of these icons myself (ok, they probably don't look awesome, but they were done with love 😁).

I can understand that for sure :P 

Some time passed by and the PR description isn't quite up to date anymore.
To clarify, the replacement icons I've chosen are [ionicons](https://ionic.io/ionicons), which core will utilize very soon, instead of tango desktop or other icon sources. Yeah, that would be the point for consistency with the modern appearance of core.

However, when I created the PR initially, the ionicion stuff was still pretty new. Currently, APIs are work in progress that allow plugin developers to utilize the ionicons provided by core in the same way how you can utilize the current icons.
Additionally, coloring ionicons based on the color scheme the user requests.
I messed a bit around with it before :P


> If you don't mind, I would appreciate a side by side comparison of before/after icons.

For sure, I'll see if I can attach one tomorrow.

**Comment by NotMyFault** [comment]
Check the PR description, I added a bunch of screenshots for the current look and the proposed changed, in light and dark mode.

**Comment by oalagtash** [comment]
I was about to open a bug report because some icons cannot be seen in dark mode. But this PR already fixed that, and the icons looks great! They also go well with the icons design in Jenkins. 
image
after highlighting, I can see the badge:
image

So yea, vote up! :)

**Comment by mawinter69** [comment]
Now with symbols in place we could use the ionicons plugin instead.
There's only 2 plugins contributing own images
Plugins could then provide a symbol or an image and
Might need a way to distinguish if a plugin provides and image. There are only 2 plugins currently providing own images both haven't been released for long time (https://www.jenkins.io/doc/developer/extensions/buildtriggerbadge/)

**Comment by NotMyFault** [comment]
Closing in favor of https://github.com/jenkinsci/buildtriggerbadge-plugin/pull/159

**Pull request closed without merging**
